version: "{build}"

os: Windows Server 2012 R2

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda-x64
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.5
      MINICONDA: C:\Miniconda3-x64

branches:
  only:
    - master

clone_folder: c:\workspace\word2vec

install:
  - set PATH=C:\\MinGW\\bin;%PATH%
  - set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%
  - echo %PATH%
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info -a

build_script:
  - conda install python=%PYTHON_VERSION% -y -q
  - conda install --file .ci/conda-requirements.txt -y -q
  - pip install -r .ci/requirements.txt
  - python setup.py bdist_wheel
  - ls dist
  - pip install --pre --no-index --find-links dist/ word2vec

test_script:
  # Test: Download test data
  - ps: mkdir $HOME/data
  - ps: wget http://mattmahoney.net/dc/text8.zip -OutFile $HOME/data/text8.zip
  # TODO: Fix Download and head of data
  # - 7z e -o %HOMEPATH%\data %HOMEPATH%\data\text8.zip
  # - Get-Content text8 -TotalCount 1MB > text
  # Test: py.test
  # - py.test -s -vv --pyarg word2vec # Test currently fail on windows
